apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: usermanagement
  template:
    metadata:
      labels:
        app: usermanagement
    spec:
      imagePullSecrets:
      - name: my-registry-secret
      containers:
      - name: usermanagement-container
        image: saishshindepersistent/usermanagement:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-db:3306/userdb
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: Nuvelabs123$
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
spec:
  type: NodePort
  selector:
    app: usermanagement
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
